### PR TITLE
update version to Angular 5

### PR DESCRIPTION
**Pull request by web-dave**
I used the version 0.7.6 with angular 5. only the version in the package.json should be updated.

### CODE REVIEW

**Comment by jenshelderweirdt** [comment]
It would be awesome if this PR could be merged...

**Comment by kush-josh** [comment]
@cstefanache @mounirrquiba Please check if it is possible for you guys to expedite this.

**Comment by sketchthat** [comment]
Is this project still maintained? Is anyone wanting to fork, build and deploy the latest changes to a new NPM package? I'm sure there are a lot of people keen to upgrade to NG5.

**Comment by jenshelderweirdt** [comment]
@cstefanache Are you still maintaining this project? Otherwise I'm willing to take over.

**Comment by akhilesh2310** [comment]
Could you please merge this pr, we really need this update

**Comment by sketchthat** [comment]
@jenshelderweirdt I emailed @cstefanache and he's unable to maintain the project anymore but is happy to assign someone else admin. I'll put your name forward.

**Comment by sketchthat** [comment]
Bump.

Anyone interested in taking over?

**Comment by zijianhuang** [comment]
I am using NG 5.10 and cropper 0.8.8, so far so good except the front camera. If none of the active contributors like Andrew Rumm rayzru, I may be interested.

**Comment by web-dave** [comment]
I'm interested to take over.

**Comment by jenshelderweirdt** [comment]
Sorry guys, it really was a hell of month. @web-dave off you go.

**Comment by web-dave** [comment]
Thx @jenshelderweirdt. So I'm waiting for to get the write access to merge this PR, right?

**Comment by web-dave** [comment]
since we use thios in ur application with angular 5.x and i found no issue, i merge it.

**Comment by sketchthat** [comment]
@web-dave do you have access to update NPM as well? https://www.npmjs.com/package/ng2-img-cropper

**Comment by web-dave** [comment]
I'm not sure, I can check it on Wednesday.

**Comment by web-dave** [comment]
Didn't get a notification

**Pull request merged**
