### PR TITLE
Improve NGC compatibility

### PR DESCRIPTION
**Pull request by cleever**
On running ngc, there are a lot of errors with visibility and methods params.

This pull request change some inputs visibilities and fix the method params to match with the html call.

### CODE REVIEW

**Comment by cstefanache** [comment]
I will try to solve the conflict by tomorrow evening so we can merge it and create a new release at the end of the week

**Comment by st1s** [comment]
@cleever have you tried with Ionic?

iOS? thoughts?

I'm just looking for a workaround because I can't get [cordova-plugin-crop](https://github.com/jeduan/cordova-plugin-crop) working on iOS

**Comment by cleever** [comment]
@st1s for Ionic you should consider using Cropperjs as described in the ionic forum:
https://forum.ionicframework.com/t/image-cropping-plugin/51206/27

**Comment by mayconjcm** [comment]
@cleever I am using angular2-img-cropper with ionic with no problems.

**Pull request merged**
