### PR TITLE
Set image without "chose file" button

### PR DESCRIPTION
**Pull request by gfranco93**
Addressing [closed issue 18](https://github.com/cstefanache/angular2-img-cropper/issues/18) from user @Mihai-B :

You just need to set the image from your app.component:
`this.data = {"image":YourImage};`

### CODE REVIEW

**Comment by Mihai-B** [comment]
This is just when you initialize the cropper. 
Using my method, you can set a new image whenever needed without re-instantiating the cropper. 
I would say this fix is not really needed.

**Comment by gfranco93** [comment]
You're right when you say that it's just for initializing the cropper, I made it that way because of the [plunker](https://embed.plnkr.co/V91mKCNkBQZB5QO2MUP4/) `this.data = {};`.

Your idea was to add a public function in ImageCropperComponent to set the image whenever needed, right? Then you will have to have add 'cropper' to the outputs of ImageCropperComponent (to avoid creating the ImageCropper outside of ImageCropperComponent).

I think both ideas can coexist, could you upload a PR?

**Comment by gfranco93** [comment]
You're right when you say that it's just for initializing the cropper, I made it that way because of the [plunker](https://embed.plnkr.co/V91mKCNkBQZB5QO2MUP4/) (`this.data = {};`).

Using you idea you will have to add 'cropper' to the outputs of ImageCropperComponent (to avoid creating the ImageCropper outside of ImageCropperComponent), am I right?

I think both ideas can coexist, could you upload a PR?

**Comment by Mihai-B** [comment]
Yes both of them can coexist. I don't need to upload a PR  because you can already implement my solution also.

Here is a quick example:
```
<div class="row">
  <img-cropper [image]="data" [settings]="cropperSettings" [cropper]="cropper"></img-cropper>
  <br>
  <img [src]="data.image" >
</div>
```
and:
`public cropper: ImageCropper;`
and in constructor:
 ```
 this.cropper = new ImageCropper(0, 0, this.cropperSettings.width, this.cropperSettings.height,
      this.cropperSettings.croppedWidth, this.cropperSettings.croppedHeight, this.cropperSettings.keepAspect);
```
And in a method where you want to add the new image for cropp:
```
let imgObj = new Image();
imgObj.src = 'data:image/png;base64,' + templateFile.fileData;
this.cropper.setImage(imgObj);
```

**Comment by gfranco93** [comment]
Great!

**Comment by cstefanache** [comment]
Is this still an issue?

**Comment by gfranco93** [comment]
No, closing.

**Pull request closed without merging**
