### PR TITLE
remove typings

### LINKED ISSUE #74: Remove dependency on typings
Angular2 no longer requires the use of typings since moving to typescript 2.0. The post_install has put a hard dependency of typings on my ci server.

```
npm install
|
> ng2-img-cropper@0.6.4 postinstall /home/ubuntu/my-project/node_modules/ng2-img-cropper
> typings install

sh: 1: typings: not found
```

### PR DESCRIPTION
**Pull request by OneOfOne**
Fixes #74

### CODE REVIEW

**Comment by OneOfOne** [comment]
This breaks compiling with webpack, trying to find out way

**Comment by cstefanache** [comment]
Any news on this one. Planning to do a release of 0.7 on monday

**Comment by OneOfOne** [comment]
It was a bug in my webpack config.

**Comment by cleever** [comment]
Any news on this?

**Comment by cstefanache** [comment]
Removed typings with #74

**Pull request closed without merging**
