### PR TITLE
Typings and cropper access

### PR DESCRIPTION
**Pull request by TwanoO67**
Hello,

Here is what we use to fix issue#65 and issue#74

I don't know if it's valid, because nether 'master' nor this branche have a working "npm start".
But this branche work when imported in our angular 2.0.1 project

### CODE REVIEW

**Comment by cstefanache** [comment]
I saw that you also removed typings -  OneOfOne did the same for #75 but for him WebPack is throwing an error. Does this happen to you as well?

**Comment by TwanoO67** [comment]
No error during compilation, but you need to update your npm packages (because of the use of @types/es6-shim )

**Comment by OneOfOne** [comment]
I didn't notice this when I made my PR, so this probably should be merged but please update angular peer to ~2.0.2.

**Comment by TwanoO67** [comment]
Ok, I updated it to angular 2.1.0

**Pull request merged**
